var map_cfg = {
    "mapWidth": "100%",
    "mapHeight": 350,
    "shadowWidth": 2,
    "shadowOpacity": 0.2,
    "shadowColor": "black",
    "shadowX": 0,
    "shadowY": 0,
    "iPhoneLink": true,
    "isNewWindow": false,
    "zoomEnable": false,
    "zoomEnableControls": false,
    "zoomIgnoreMouseScroll": false,
    "zoomMax": 8,
    "zoomStep": 0.8,
    "borderColor": "#ffffff",
    "borderColorOver": "#ffffff",
    "borderOpacity": 0.5,
    "nameColor": "#ffffff",
    "nameColorOver": "#ffffff",
    "nameFontSize": "10px",
    "nameFontWeight": "bold",
    "nameStroke": true,
    "nameStrokeColor": "#000000",
    "nameStrokeColorOver": "#000000",
    "nameStrokeWidth": 1.5,
    "nameStrokeOpacity": 0.5,
    "overDelay": 300,
    "nameAutoSize": false,
    "tooltipOnHighlightIn": false,
    "freezeTooltipOnClick": false,
    "mapId": "gXo5J",
    "map_data": {
        "st1": {
            "id": 1,
            "name": "Far Eastern Federal District",
            "shortname": "69.15\n(FEFD)",
            "comment": "",
            "image": "",
            "color": "#f9e600",
            "colorOver": "#366CA3"
        },
        "st2": {
            "id": 2,
            "name": "Volga Federal District",
            "shortname": "70.83\n(VFD)",
            "comment": "",
            "image": "",
            "color": "#deff00",
            "colorOver": "#366CA3"
        },
        "st3": {
            "id": 3,
            "name": "Northwestern Federal District",
            "shortname": "72.02\n(NWFD)",
            "comment": "",
            "image": "",
            "color": "#deff00",
            "colorOver": "#366CA3"
        },
        "st4": {
            "id": 4,
            "name": "North Caucasian Federal District",
            "shortname": "74.58\n(NCFD)",
            "comment": "",
            "image": "",
            "color": "#9ad100",
            "colorOver": "#366CA3",
            "borderColor": "red",
            "borderColorOver": "red"
        },
        "st5": {
            "id": 5,
            "name": "Siberian Federal District",
            "shortname": "69.60\n(SibFD)",
            "comment": "",
            "image": "",
            "color": "#f9e600",
            "colorOver": "#366CA3"
        },
        "st6": {
            "id": 6,
            "name": "Ural Federal District",
            "shortname": "70.81\n(UFD)",
            "comment": "",
            "image": "",
            "color": "#deff00",
            "colorOver": "#366CA3"
        },
        "st7": {
            "id": 7,
            "name": "Central Federal District",
            "shortname": "72.57\n(CFD)",
            "comment": "",
            "image": "",
            "color": "#9ad100",
            "colorOver": "#366CA3"
        },
        "st8": {
            "id": 8,
            "name": "Southern Federal District",
            "shortname": "72.09\n(SFD)",
            "comment": "",
            "image": "",
            "color": "#deff00",
            "colorOver": "#366CA3"
        }
    },
    "points": {}
};
