replacements_fr = {
    'Hong Kong SAR, China' : 'Hong Kong',
    'Kuwait' : 'Koweït',
    'Switzerland' : 'Suisse',
    'French Polynesia' : 'Polynésie française',
    'Andorra' : 'Andorre',
    'Sweden' : 'Suède',
    'Japan' : 'Japon',
    'Italy' : 'Italie',
    'Spain' : 'Espagne',
    'South Korea' : 'Corée du Sud',
    'Singapore' : 'Singapour',
    'Macao SAR, China' : 'Macao',
    'Israel' : 'Israël',
    'Luxembourg' : 'Luxembourg',
    'Norway' : 'Norvège',
    'Faroe Islands' : 'Îles Féroé',
    'United Arab Emirates' : 'Émirats arabes unis',
    'Australia' : 'Australie',
    'Ireland' : 'Irlande',
    'France' : 'France',
    'Malta' : 'Malte',
    'Iceland' : 'Islande',
    'Qatar' : 'Qatar',
    'Bermuda' : 'Bermudes',
    'Portugal' : 'Portugal',
    'Finland' : 'Finlande',
    'Belgium' : 'Belgique',
    'Slovenia' : 'Slovénie',
    'Denmark' : 'Danemark',
    'Canada' : 'Canada',
    'New Zealand' : 'Nouvelle-Zélande',
    'Austria' : 'Autriche',
    'Netherlands' : 'Pays-Bas',
    'Puerto Rico' : 'Porto Rico',
    'Greece' : 'Grèce',
    'Cyprus' : 'Chypre',
    'Bahrain' : 'Bahreïn',
    'United Kingdom' : 'Royaume-Uni',
    'Chile' : 'Chili',
    'Maldives' : 'Maldives',
    'Channel Islands' : 'Îles Anglo-Normandes',
    'Isle of Man' : 'Île de Man',
    'Costa Rica' : 'Costa Rica',
    'Germany' : 'Allemagne',
    'Virgin Islands (U.S.)' : 'Îles Vierges des États-Unis',
    'Cayman Islands' : 'Îles Caïmans',
    'Oman' : 'Oman',
    'Czechia' : 'Tchéquie',
    'Albania' : 'Albanie',
    'Panama' : 'Panama',
    'Estonia' : 'Estonie',
    'Saudi Arabia' : 'Arabie saoudite',
    'Northern Mariana Islands' : 'Îles Mariannes du Nord',
    'Croatia' : 'Croatie',
    'New Caledonia' : 'Nouvelle-Calédonie',
    'USA' : 'États-Unis',
    'Poland' : 'Pologne',
    'Slovakia' : 'Slovaquie',
    'Armenia' : 'Arménie',
    'Uruguay' : 'Uruguay',
    'Cuba' : 'Cuba',
    'Bosnia and Herzegovina' : 'Bosnie-Herzégovine',
    'Bosnia & Herzegovina' : 'Bosnie-Herzégovine',
    'China' : 'Chine',
    'Jordan' : 'Jordanie',
    'Lebanon' : 'Liban',
    'Peru' : 'Pérou',
    'Colombia' : 'Colombie',
    'Montenegro' : 'Monténégro',
    'Iran' : 'Iran',
    'Antigua and Barbuda' : 'Antigua-et-Barbuda',
    'Sri Lanka' : 'Sri Lanka',
    'Ecuador' : 'Équateur',
    'Argentina' : 'Argentine',
    'Guam' : 'Guam',
    'Turkey' : 'Turquie',
    'Lithuania' : 'Lituanie',
    'Curacao' : 'Curaçao',
    'Malaysia' : 'Malaisie',
    'Hungary' : 'Hongrie',
    'Tunisia' : 'Tunisie',
    'North Macedonia' : 'Macédoine du Nord',
    'Thailand' : 'Thaïlande',
    'Sint Maarten' : 'Sint Maarten',
    'Aruba' : 'Aruba',
    'Algeria' : 'Algérie',
    'Romania' : 'Roumanie',
    'Latvia' : 'Lettonie',
    'Barbados' : 'Barbade',
    'Seychelles' : 'Seychelles',
    'Cabo Verde' : 'Cap-Vert',
    'Brazil' : 'Brésil',
    'Serbia' : 'Serbie',
    'Bulgaria' : 'Bulgarie',
    'Brunei' : 'Brunei',
    'Morocco' : 'Maroc',
    'Grenada' : 'Grenade',
    'Mexico' : 'Mexique',
    'Nicaragua' : 'Nicaragua',
    'Bangladesh' : 'Bangladesh',
    'Vietnam' : 'Vietnam',
    'Bahamas' : 'Bahamas',
    'Ukraine' : 'Ukraine',
    'Georgia' : 'Géorgie',
    'Azerbaijan' : 'Azerbaïdjan',
    'Kazakhstan' : 'Kazakhstan',
    'Belarus' : 'Biélorussie',
    'Paraguay' : 'Paraguay',
    'Dominican Republic' : 'République dominicaine',
    'Mauritius' : 'Maurice',
    'Suriname' : 'Suriname',
    'North Korea' : 'Corée du Nord',
    'Belize' : 'Belize',
    'Trinidad and Tobago' : 'Trinité-et-Tobago',
    'Russia' : 'Russie',
    'Bhutan' : 'Bhoutan',
    'Tonga' : 'Tonga',
    'Honduras' : 'Honduras',
    'St. Lucia' : 'Sainte-Lucie',
    'Guatemala' : 'Guatemala',
    'Venezuela' : 'Venezuela',
    'Syria' : 'Syrie',
    'Uzbekistan' : 'Ouzbékistan',
    'Iraq' : 'Irak',
    'Kyrgyzstan' : 'Kirghizistan',
    'Mongolia' : 'Mongolie',
    'El Salvador' : 'Salvador',
    'India' : 'Inde',
    'Tajikistan' : 'Tadjikistan',
    'Samoa' : 'Samoa',
    'Egypt' : 'Égypte',
    'Vanuatu' : 'Vanuatu',
    'Jamaica' : 'Jamaïque',
    'St. Vincent and the Grenadines' : 'Saint-Vincent-et-les-Grenadines',
    'Moldova' : 'Moldavie',
    'Dominica' : 'Dominique',
    'Indonesia' : 'Indonésie',
    'Libya' : 'Libye',
    'Cambodia' : 'Cambodge',
    'Solomon Islands' : 'Îles Salomon',
    'Nepal' : 'Népal',
    'Guyana' : 'Guyana',
    'Greenland' : 'Groenland',
    'Turkmenistan' : 'Turkménistan',
    'Philippines' : 'Philippines',
    'Sao Tome and Principe' : 'Sao Tomé-et-Principe',
    'Yemen' : 'Yémen',
    'Botswana' : 'Botswana',
    'Laos' : 'Laos',
    'Palestine' : 'Palestine',
    'Senegal' : 'Sénégal',
    'Eritrea' : 'Érythrée',
    'Bolivia' : 'Bolivie',
    'Mauritania' : 'Mauritanie',
    'Gabon' : 'Gabon',
    'Uganda' : 'Ouganda',
    'Rwanda' : 'Rwanda',
    'Timor-Leste' : 'Timor-Leste',
    'Pakistan' : 'Pakistan',
    'Ethiopia' : 'Éthiopie',
    'Malawi' : 'Malawi',
    'Namibia' : 'Namibie',
    'Fiji' : 'Fidji',
    'Micronesia' : 'Micronésie',
    'Tanzania' : 'Tanzanie',
    'Myanmar' : 'Myanmar',
    'Comoros' : 'Comores',
    'Kiribati' : 'Kiribati',
    'Zambia' : 'Zambie',
    'Sudan' : 'Soudan',
    'South Africa' : 'Afrique du Sud',
    'Afghanistan' : 'Afghanistan',
    'Papua New Guinea' : 'Papouasie-Nouvelle-Guinée',
    'Djibouti' : 'Djibouti',
    'Gambia' : 'Gambie',
    'Congo, Rep.' : 'Congo',
    'Ghana' : 'Ghana',
    'Haiti' : 'Haïti',
    'Angola' : 'Angola',
    'Eswatini' : 'Eswatini',
    'Guinea-Bissau' : 'Guinée-Bissau',
    'Cameroon' : 'Cameroun',
    'Equatorial Guinea' : 'Guinée équatoriale',
    'Madagascar' : 'Madagascar',
    'Kenya' : 'Kenya',
    'Burundi' : 'Burundi',
    'Mozambique' : 'Mozambique',
    'Zimbabwe' : 'Zimbabwe',
    'Togo' : 'Togo',
    'Liberia' : 'Liberia',
    "Cote d'Ivoire" : "Côte d'Ivoire",
    'DR Congo' : 'RD Congo',
    'Sierra Leone' : 'Sierra Leone',
    'Niger' : 'Niger',
    'Burkina Faso' : 'Burkina Faso',
    'Benin' : 'Bénin',
    'Guinea' : 'Guinée',
    'Mali' : 'Mali',
    'Somalia' : 'Somalie',
    'Lesotho' : 'Lesotho',
    'South Sudan' : 'Soudan du Sud',
    'Central African Republic' : 'Centrafrique',
    'Chad' : 'Tchad',
    'Nigeria' : 'Nigeria',
    'Kosovo' : 'Kosovo',
    'Liechtenstein' : 'Liechtenstein',
    'San Marino' : 'Saint-Marin',
    'Monaco' : 'Monaco'
}